name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8

      - name: Lint
        run: flake8 . --max-line-length=120 --extend-exclude=.venv,venv

      - name: Test
        run: pytest -q

      - name: Build dashboard artifact (optional)
        run: |
          mkdir -p dist
          cp -r dashboard dist/dashboard

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dashboard
          path: dist/dashboard
